const mongoose = require('mongoose');
const Question = require('./models/Question');
const connectDB = require('./config/db');
require('dotenv').config({ path: '../.env' });

const mockData = [
    // --- DIFFICULTY 1: WEB FUNDAMENTALS & BASIC DB (11 câu) ---
    { content: "Thẻ <head> trong HTML dùng để làm gì?", options: [{ id: 1, text: "Chứa thông tin meta, tiêu đề và link CSS" }, { id: 2, text: "Hiển thị nội dung chính của trang web" }, { id: 3, text: "Định nghĩa kiểu font chữ" }, { id: 4, text: "Tạo animation" }], correctAnswerIds: [1], difficulty: 1 },
    { content: "Trong SQL, từ khóa nào dùng để lấy dữ liệu?", options: [{ id: 1, text: "GET" }, { id: 2, text: "SELECT" }, { id: 3, text: "FETCH" }, { id: 4, text: "READ" }], correctAnswerIds: [2], difficulty: 1 },
    { content: "Primary Key (Khóa chính) trong Database dùng để làm gì?", options: [{ id: 1, text: "Định danh duy nhất cho mỗi bản ghi" }, { id: 2, text: "Dùng để mã hóa dữ liệu" }, { id: 3, text: "Tăng tốc độ truy vấn" }, { id: 4, text: "Xóa dữ liệu cũ" }], correctAnswerIds: [1], difficulty: 1 },
    { content: "Kiểu dữ liệu nào dùng để lưu trữ văn bản dài trong JS?", options: [{ id: 1, text: "String" }, { id: 2, text: "Boolean" }, { id: 3, text: "Number" }, { id: 4, text: "Array" }], correctAnswerIds: [1], difficulty: 1 },
    { content: "CSS Box Model gồm những thành phần nào?", options: [{ id: 1, text: "Margin, Border, Padding, Content" }, { id: 2, text: "Header, Footer, Main, Aside" }, { id: 3, text: "Width, Height, Color, Font" }, { id: 4, text: "Display, Position, Flex, Grid" }], correctAnswerIds: [1], difficulty: 1 },
    { content: "Lệnh 'DELETE' khác gì 'TRUNCATE' trong SQL?", options: [{ id: 1, text: "DELETE có thể dùng WHERE, TRUNCATE xóa toàn bộ bảng nhanh hơn" }, { id: 2, text: "Giống hệt nhau" }, { id: 3, text: "DELETE nhanh hơn TRUNCATE" }, { id: 4, text: "TRUNCATE có thể dùng WHERE" }], correctAnswerIds: [1], difficulty: 1 },
    { content: "Trong JavaScript, mảng (Array) là một kiểu của?", options: [{ id: 1, text: "Object" }, { id: 2, text: "Primitive" }, { id: 3, text: "Function" }, { id: 4, text: "String" }], correctAnswerIds: [1], difficulty: 1 },
    { content: "Thẻ <script> thường được đặt ở đâu để tối ưu tốc độ load trang?", options: [{ id: 1, text: "Cuối thẻ <body>" }, { id: 2, text: "Đầu thẻ <head>" }, { id: 3, text: "Trong thẻ <div>" }, { id: 4, text: "Ngoài HTML" }], correctAnswerIds: [1], difficulty: 1 },
    { content: "Dấu '!' trong logic lập trình có nghĩa là gì?", options: [{ id: 1, text: "Phép phủ định (NOT)" }, { id: 2, text: "Phép gán" }, { id: 3, text: "Phép cộng" }, { id: 4, text: "Phép so sánh" }], correctAnswerIds: [1], difficulty: 1 },
    { content: "Trong SQL, 'ORDER BY' dùng để làm gì?", options: [{ id: 1, text: "Sắp xếp kết quả trả về" }, { id: 2, text: "Lọc dữ liệu theo điều kiện" }, { id: 3, text: "Nhóm dữ liệu" }, { id: 4, text: "Xóa dữ liệu" }], correctAnswerIds: [1], difficulty: 1 },
    { content: "Responsive Design có mục đích gì?", options: [{ id: 1, text: "Giúp trang web hiển thị tốt trên nhiều thiết bị" }, { id: 2, text: "Giúp trang web chạy nhanh hơn" }, { id: 3, text: "Tăng dung lượng server" }, { id: 4, text: "Giảm số người truy cập" }], correctAnswerIds: [1], difficulty: 1 },

    // --- DIFFICULTY 2: INTERMEDIATE DEV & DB RELATIONSHIPS (11 câu) ---
    { content: "Foreign Key (Khóa ngoại) dùng để làm gì?", options: [{ id: 1, text: "Tạo liên kết giữa hai bảng" }, { id: 2, text: "Tăng tốc độ tìm kiếm" }, { id: 3, text: "Mã hóa dữ liệu" }, { id: 4, text: "Xóa bảng cũ" }], correctAnswerIds: [1], difficulty: 2 },
    { content: "Trong Git, lệnh nào dùng để đưa code từ local lên server?", options: [{ id: 1, text: "git pull" }, { id: 2, text: "git push" }, { id: 3, text: "git fetch" }, { id: 4, text: "git clone" }], correctAnswerIds: [2], difficulty: 2 },
    { content: "Sự khác biệt giữa INNER JOIN và LEFT JOIN?", options: [{ id: 1, text: "LEFT JOIN lấy cả các bản ghi không khớp ở bảng bên trái" }, { id: 2, text: "INNER JOIN lấy toàn bộ dữ liệu 2 bảng" }, { id: 3, text: "LEFT JOIN nhanh hơn INNER JOIN" }, { id: 4, text: "INNER JOIN lấy cả dữ liệu 2 bảng" }], correctAnswerIds: [1], difficulty: 2 },
    { content: "Trạng thái HTTP 404 có nghĩa là gì?", options: [{ id: 1, text: "Server Error" }, { id: 2, text: "Not Found" }, { id: 3, text: "Bad Request" }, { id: 4, text: "Unauthorized" }], correctAnswerIds: [2], difficulty: 2 },
    { content: "State trong React khác gì Props?", options: [{ id: 1, text: "State có thể thay đổi bên trong component, Props là dữ liệu truyền vào" }, { id: 2, text: "Props là private, State là public" }, { id: 3, text: "State nhanh hơn Props" }, { id: 4, text: "Giống hệt nhau" }], correctAnswerIds: [1], difficulty: 2 },
    { content: "Lệnh 'GROUP BY' trong SQL thường đi kèm với hàm nào?", options: [{ id: 1, text: "COUNT, SUM, AVG" }, { id: 2, text: "SELECT, INSERT" }, { id: 3, text: "WHERE, ORDER BY" }, { id: 4, text: "JOIN, UNION" }], correctAnswerIds: [1], difficulty: 2 },
    { content: "Arrow Function trong ES6 khác gì function thường?", options: [{ id: 1, text: "Không có 'this' riêng" }, { id: 2, text: "Chạy chậm hơn" }, { id: 3, text: "Cú pháp ngắn gọn hơn" }, { id: 4, text: "Không thể dùng async" }], correctAnswerIds: [1, 3], difficulty: 2 },
    { content: "Trong SQL, làm thế nào để tránh trùng lặp kết quả?", options: [{ id: 1, text: "Dùng từ khóa DISTINCT" }, { id: 2, text: "Dùng từ khóa UNIQUE" }, { id: 3, text: "Dùng GROUP BY" }, { id: 4, text: "Không thể tránh" }], correctAnswerIds: [1], difficulty: 2 },
    { content: "npm install --save-dev dùng để làm gì?", options: [{ id: 1, text: "Cài đặt thư viện chỉ dùng trong môi trường phát triển" }, { id: 2, text: "Cài đặt thư viện lên production" }, { id: 3, text: "Cập nhật tất cả thư viện" }, { id: 4, text: "Xóa thư viện" }], correctAnswerIds: [1], difficulty: 2 },
    { content: "Flexbox trong CSS dùng để làm gì?", options: [{ id: 1, text: "Dàn trang linh hoạt theo hàng hoặc cột" }, { id: 2, text: "Tạo hiệu ứng 3D" }, { id: 3, text: "Tạo animation" }, { id: 4, text: "Quản lý font chữ" }], correctAnswerIds: [1], difficulty: 2 },
    { content: "Xử lý bất đồng bộ cơ bản nhất trong JS là?", options: [{ id: 1, text: "Callback" }, { id: 2, text: "Loop" }, { id: 3, text: "Promise" }, { id: 4, text: "async/await" }], correctAnswerIds: [1], difficulty: 2 },

    // --- DIFFICULTY 3: ADVANCED DEV & DB ARCHITECTURE (11 câu) ---
    { content: "ACID trong Database viết tắt của gì?", options: [{ id: 1, text: "Atomicity, Consistency, Isolation, Durability" }, { id: 2, text: "Access, Control, Index, Data" }, { id: 3, text: "Append, Create, Import, Delete" }, { id: 4, text: "Authentication, Cache, Input, Display" }], correctAnswerIds: [1], difficulty: 3 },
    { content: "React.memo() dùng để làm gì?", options: [{ id: 1, text: "Tránh re-render component nếu props không đổi" }, { id: 2, text: "Lưu dữ liệu vào bộ nhớ máy" }, { id: 3, text: "Tối ưu hóa JavaScript" }, { id: 4, text: "Xóa component" }], correctAnswerIds: [1], difficulty: 3 },
    { content: "Mục đích của Database Normalization (Chuẩn hóa)?", options: [{ id: 1, text: "Giảm dư thừa dữ liệu và đảm bảo tính nhất quán" }, { id: 2, text: "Để dữ liệu chiếm nhiều dung lượng hơn" }, { id: 3, text: "Tăng tốc độ database" }, { id: 4, text: "Xóa các cột không dùng" }], correctAnswerIds: [1], difficulty: 3 },
    { content: "Middleware trong Node.js/Express là gì?", options: [{ id: 1, text: "Hàm trung gian xử lý Request trước khi đến Controller" }, { id: 2, text: "Một loại cơ sở dữ liệu" }, { id: 3, text: "Plugin cho frontend" }, { id: 4, text: "Giao thức mạng" }], correctAnswerIds: [1], difficulty: 3 },
    { content: "Sự khác biệt giữa PUT và PATCH?", options: [{ id: 1, text: "PUT thay thế toàn bộ, PATCH cập nhật một phần" }, { id: 2, text: "PATCH nhanh hơn PUT" }, { id: 3, text: "PUT chỉ dùng cho cập nhật" }, { id: 4, text: "Giống hệt nhau" }], correctAnswerIds: [1], difficulty: 3 },
    { content: "Trong SQL, 'HAVING' khác 'WHERE' ở điểm nào?", options: [{ id: 1, text: "HAVING dùng để lọc sau khi đã GROUP BY" }, { id: 2, text: "Giống hệt nhau" }, { id: 3, text: "WHERE nhanh hơn HAVING" }, { id: 4, text: "HAVING dùng cho tất cả câu lệnh" }], correctAnswerIds: [1], difficulty: 3 },
    { content: "Controlled Component trong React là gì?", options: [{ id: 1, text: "Component có dữ liệu form được quản lý bởi State" }, { id: 2, text: "Component không thể bị xóa" }, { id: 3, text: "Component hiển thị dữ liệu cố định" }, { id: 4, text: "Component không có props" }], correctAnswerIds: [1], difficulty: 3 },
    { content: "Tại sao nên dùng mảng để lưu danh sách ID trong MongoDB?", options: [{ id: 1, text: "Để thực hiện các truy vấn quan hệ kiểu One-to-Many nhanh" }, { id: 2, text: "MongoDB không hỗ trợ bảng" }, { id: 3, text: "Tiết kiệm dung lượng" }, { id: 4, text: "Không có lý do" }], correctAnswerIds: [1], difficulty: 3 },
    { content: "Hàm .reduce() trong JS dùng để làm gì?", options: [{ id: 1, text: "Biến đổi mảng thành một giá trị duy nhất" }, { id: 2, text: "Xóa các phần tử trong mảng" }, { id: 3, text: "Sắp xếp mảng" }, { id: 4, text: "Lọc phần tử mảng" }], correctAnswerIds: [1], difficulty: 3 },
    { content: "Virtual DOM giúp React nhanh hơn nhờ?", options: [{ id: 1, text: "Chỉ cập nhật những phần thực sự thay đổi trên Real DOM" }, { id: 2, text: "Bỏ qua CSS" }, { id: 3, text: "Xóa JavaScript" }, { id: 4, text: "Không có tác dụng" }], correctAnswerIds: [1], difficulty: 3 },
    { content: "Trong Database, 'Transaction' là gì?", options: [{ id: 1, text: "Một nhóm các câu lệnh SQL thực thi như một đơn vị duy nhất" }, { id: 2, text: "Lịch sử mua hàng" }, { id: 3, text: "Một bảng trong database" }, { id: 4, text: "Kết nối server" }], correctAnswerIds: [1], difficulty: 3 },

    // --- DIFFICULTY 4: SYSTEM PERFORMANCE & DB TUNING (11 câu) ---
    { content: "B-Tree Index hoạt động thế nào trong SQL?", options: [{ id: 1, text: "Sắp xếp dữ liệu theo dạng cây để tìm kiếm với độ phức tạp O(log n)" }, { id: 2, text: "Quét toàn bộ bảng từ đầu đến cuối" }, { id: 3, text: "Dùng hashtable" }, { id: 4, text: "Sử dụng linked list" }], correctAnswerIds: [1], difficulty: 4 },
    { content: "Tại sao không nên đánh Index cho tất cả các cột?", options: [{ id: 1, text: "Làm chậm thao tác ghi (INSERT/UPDATE)" }, { id: 2, text: "Làm database bị lỗi" }, { id: 3, text: "Tiêu tốn quá nhiều bộ nhớ" }, { id: 4, text: "Không có lý do" }], correctAnswerIds: [1, 3], difficulty: 4 },
    { content: "JWT (JSON Web Token) gồm 3 phần nào?", options: [{ id: 1, text: "Header, Payload, Signature" }, { id: 2, text: "Username, Password, Salt" }, { id: 3, text: "Token, Key, Data" }, { id: 4, text: "Encrypt, Hash, Random" }], correctAnswerIds: [1], difficulty: 4 },
    { content: "Cơ chế 'Sharding' trong Database là gì?", options: [{ id: 1, text: "Chia nhỏ một Database lớn thành nhiều server vật lý" }, { id: 2, text: "Sao chép dữ liệu để dự phòng" }, { id: 3, text: "Nén dữ liệu" }, { id: 4, text: "Tạo backup" }], correctAnswerIds: [1], difficulty: 4 },
    { content: "Event Delegation trong JavaScript là gì?", options: [{ id: 1, text: "Gắn sự kiện vào phần tử cha để quản lý các phần tử con" }, { id: 2, text: "Xóa bỏ sự kiện" }, { id: 3, text: "Tạo sự kiện mới" }, { id: 4, text: "Từ chối sự kiện" }], correctAnswerIds: [1], difficulty: 4 },
    { content: "Sự khác biệt giữa NoSQL (Document) và RDBMS?", options: [{ id: 1, text: "NoSQL schema linh hoạt, RDBMS schema cố định" }, { id: 2, text: "RDBMS luôn nhanh hơn NoSQL" }, { id: 3, text: "NoSQL không thể store dữ liệu" }, { id: 4, text: "RDBMS dùng cho web 3" }], correctAnswerIds: [1], difficulty: 4 },
    { content: "Tại sao dùng Redis làm Cache?", options: [{ id: 1, text: "Vì nó lưu trữ trên RAM, tốc độ đọc ghi cực nhanh" }, { id: 2, text: "Vì nó lưu trữ được nhiều dữ liệu hơn ổ cứng" }, { id: 3, text: "Vì nó là open source" }, { id: 4, text: "Vì nó có giao diện đẹp" }], correctAnswerIds: [1], difficulty: 4 },
    { content: "CORS (Cross-Origin Resource Sharing) là gì?", options: [{ id: 1, text: "Cơ chế bảo mật trình duyệt ngăn gọi API khác domain" }, { id: 2, text: "Một giao thức mạng mới" }, { id: 3, text: "Loại cookie" }, { id: 4, text: "Mã hóa dữ liệu" }], correctAnswerIds: [1], difficulty: 4 },
    { content: "Thế nào là 'N+1 Query Problem' trong ORM?", options: [{ id: 1, text: "Gây ra quá nhiều câu lệnh SQL lẻ tẻ khi lấy dữ liệu liên quan" }, { id: 2, text: "Lỗi cú pháp SQL" }, { id: 3, text: "Tình huống database bị lỗi" }, { id: 4, text: "Lỗi khi compile code" }], correctAnswerIds: [1], difficulty: 4 },
    { content: "Hàm 'bind' trong JS dùng để làm gì?", options: [{ id: 1, text: "Tạo một hàm mới với giá trị 'this' được chỉ định" }, { id: 2, text: "Nối hai chuỗi" }, { id: 3, text: "Xóa dữ liệu" }, { id: 4, text: "Tạo object mới" }], correctAnswerIds: [1], difficulty: 4 },
    { content: "Database Replication mục đích chính là?", options: [{ id: 1, text: "Tăng tính sẵn sàng và khả năng chịu lỗi" }, { id: 2, text: "Tiết kiệm dung lượng" }, { id: 3, text: "Tăng tốc độ lưu trữ" }, { id: 4, text: "Giảm chi phí server" }], correctAnswerIds: [1], difficulty: 4 },

    // --- DIFFICULTY 5: SENIOR ARCHITECTURE & COMPLEX DB (11 câu) ---
    { content: "CAP Theorem khẳng định điều gì trong hệ thống phân tán?", options: [{ id: 1, text: "Chỉ có thể chọn 2 trong 3: Consistency, Availability, Partition Tolerance" }, { id: 2, text: "Database luôn phải có 3 tính chất" }, { id: 3, text: "Tất cả hệ thống phân tán đều có CAP" }, { id: 4, text: "Không thể chọn bất kỳ tính chất nào" }], correctAnswerIds: [1], difficulty: 5 },
    { content: "Sự khác biệt giữa Optimistic và Pessimistic Locking?", options: [{ id: 1, text: "Optimistic check phiên bản khi update, Pessimistic khóa dòng dữ liệu ngay từ đầu" }, { id: 2, text: "Optimistic chậm hơn Pessimistic" }, { id: 3, text: "Optimistic luôn an toàn hơn" }, { id: 4, text: "Pessimistic không sử dụng database" }], correctAnswerIds: [1], difficulty: 5 },
    { content: "Cơ chế 'Event Loop' xử lý Microtasks (Promise) và Macrotasks (setTimeout) thế nào?", options: [{ id: 1, text: "Xử lý hết toàn bộ Microtasks trước khi sang Macrotask tiếp theo" }, { id: 2, text: "Xử lý xen kẽ 1-1" }, { id: 3, text: "Chỉ xử lý Microtasks" }, { id: 4, text: "Chỉ xử lý Macrotasks" }], correctAnswerIds: [1], difficulty: 5 },
    { content: "Làm thế nào để tối ưu một truy vấn SQL chạy chậm?", options: [{ id: 1, text: "Dùng EXPLAIN để phân tích execution plan và đánh index phù hợp" }, { id: 2, text: "Xóa bớt dữ liệu" }, { id: 3, text: "Tăng RAM server" }, { id: 4, text: "Không thể tối ưu" }], correctAnswerIds: [1], difficulty: 5 },
    { content: "CQRS (Command Query Responsibility Segregation) là gì?", options: [{ id: 1, text: "Tách biệt logic ghi (Command) và đọc (Query) dữ liệu" }, { id: 2, text: "Một cách đặt tên biến" }, { id: 3, text: "Mẫu lập trình không tồn tại" }, { id: 4, text: "Loại API" }], correctAnswerIds: [1], difficulty: 5 },
    { content: "Tại sao 'Deep Equality' trong JS lại tốn kém tài nguyên?", options: [{ id: 1, text: "Phải đệ quy qua toàn bộ các thuộc tính của object lồng nhau" }, { id: 2, text: "Vì nó so sánh địa chỉ ô nhớ" }, { id: 3, text: "Vì nó cần compile" }, { id: 4, text: "Vì JavaScript chậm" }], correctAnswerIds: [1], difficulty: 5 },
    { content: "Database Index lồng (Composite Index) hoạt động hiệu quả nhất khi?", options: [{ id: 1, text: "Truy vấn tuân theo quy tắc 'Leftmost Prefix'" }, { id: 2, text: "Truy vấn cột nào cũng được" }, { id: 3, text: "Index lồng luôn vô dụng" }, { id: 4, text: "Không có quy tắc" }], correctAnswerIds: [1], difficulty: 5 },
    { content: "Trong Node.js, Worker Threads dùng để làm gì?", options: [{ id: 1, text: "Xử lý các tác vụ tính toán nặng (CPU intensive) mà không làm block Event Loop" }, { id: 2, text: "Xử lý Request của người dùng" }, { id: 3, text: "Quản lý database" }, { id: 4, text: "Tạo web interface" }], correctAnswerIds: [1], difficulty: 5 },
    { content: "Giao thức gRPC sử dụng cái gì để truyền tải dữ liệu hiệu quả hơn REST?", options: [{ id: 1, text: "HTTP/2 và Protocol Buffers (Binary)" }, { id: 2, text: "JSON và HTTP/1.1" }, { id: 3, text: "XML và WebSocket" }, { id: 4, text: "CSV và FTP" }], correctAnswerIds: [1], difficulty: 5 },
    { content: "Tính chất 'Isolation' trong ACID ở mức 'Serializable' có ý nghĩa gì?", options: [{ id: 1, text: "Đảm bảo kết quả giống như các transaction chạy tuần tự" }, { id: 2, text: "Cho phép đọc dữ liệu rác (Dirty Read)" }, { id: 3, text: "Cho phép transaction xung đột" }, { id: 4, text: "Không có ý nghĩa gì" }], correctAnswerIds: [1], difficulty: 5 },
    { content: "Làm thế nào để xử lý 'Race Condition' khi hai request cùng cập nhật số dư ví điện tử?", options: [{ id: 1, text: "Sử dụng Atomic Update hoặc Database Lock" }, { id: 2, text: "Dùng if-else ở code backend" }, { id: 3, text: "Không thể xử lý race condition" }, { id: 4, text: "Tạo thread mới" }], correctAnswerIds: [1], difficulty: 5 }
];

const seed = async () => {
    try {
        await connectDB();
        await Question.deleteMany({});
        await Question.insertMany(mockData);
        console.log("Seeded 55 high-quality questions successfully with 4 options each!");
        process.exit();
    } catch (err) {
        console.error(" Error seeding data:", err);
        process.exit(1);
    }
};
seed();
